const googleCloudZones = [
  // "northamerica-northeast1-a",
  // "northamerica-northeast1-b",
  // "northamerica-northeast1-c",
  // "northamerica-northeast2-a",
  // "northamerica-northeast2-b",
  // "northamerica-northeast2-c",
  // "us-central1-a",
  "us-central1-b",
  "us-central1-c",
  "us-central1-f",
  "us-east1-b",
  "us-east1-c",
  "us-east1-d",
  "us-east4-a",
  "us-east4-b",
  "us-east4-c",
  "us-west1-a",
  "us-west1-b",
  "us-west1-c",
  "us-west2-a",
  "us-west2-b",
  "us-west2-c",
  "us-west3-a",
  "us-west3-b",
  "us-west3-c",
  "us-west4-a",
  "us-west4-b",
  "us-west4-c",
];

module.exports = {
  googleCloudZones,
};
