services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: ${STRIPE_CONTAINER_NAME}
    working_dir: /usr/src/app
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    networks:
      gmrscrap-network:
        ipv4_address: ${STRIPE_IP}
    volumes:
      - ${SOURCE_PATH}/stripe-secrets:/usr/src/app/secrets
    entrypoint: >
      sh -c "
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --print-secret > /usr/src/app/secrets/stripe_webhook_secret && 
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://${SERVER_IP}:${SERVER_PORT}/stripe/webhook
      "
  docker:
    image: ${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER_NAME}
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "${DOCKER_PORT}:2375"
    working_dir: ${DOCKER_WORKING_DIR}
    networks:
      gmrscrap-network:
        ipv4_address: ${DOCKER_IP}
  machine:
    build:
      context: ${MACHINE_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${MACHINE_CONTAINER_NAME}
    volumes:
      - ${SOURCE_PATH}/firebase.json:/usr/src/app/firebase.json
      - ${SOURCE_PATH}/firebasekeys.json:/usr/src/app/firebasekeys.json
      - ${SOURCE_PATH}/machine:/usr/src/app
    working_dir: ${MACHINE_WORKING_DIR}
    environment:
      NODE_ENV: development
      DOCKER_HOST: ${DOCKER_IP}
      DOCKER_PORT: ${DOCKER_PORT}
      MACHINE_BUILD_IMAGE_NAME: ${MACHINE_BUILD_IMAGE_NAME}
    networks:
      gmrscrap-network:
        ipv4_address: ${MACHINE_IP}
    restart: "no"
    depends_on:
      - docker
    entrypoint: ["npm", "run", "init"]
  firebase:
    # depends_on:
    #   - machine
    build:
      context: ${FIREBASE_BUILD_CONTEXT}
      dockerfile: Dockerfile
    volumes:
      - ${SOURCE_PATH}/functions/index.js:/usr/src/app/functions/index.js
      - ${SOURCE_PATH}/functions/src:/usr/src/app/functions/src
    container_name: ${FIREBASE_CONTAINER_NAME}
    ports:
      - "9099:9099"
      - "5002:5002"
      - "4000:4000"
      - "5001:5001"
      - "9299:9299"
      - "9000:9000"
      - "8080:8080"
      - "9199:9199"
      # - "5000:5000"
      - "8085:8085"
      - "4400:4400"
    # - "${VITE_FIREBASE_FUNCTIONS_EMULATOR_PORT}:5001"
    # - "${VITE_FIRESTORE_EMULATOR_PORT}:9100"
    # - "${VITE_STORAGE_EMULATOR_PORT}:9199"
    # - "${VITE_FIREBASE_AUTH_EMULATOR_PORT}:9099"
    # - "${VITE_UI_EMULATOR_PORT}:4000"
    networks:
      gmrscrap-network:
        ipv4_address: ${FIREBASE_IP}
  client:
    build:
      context: ${CLIENT_BUILD_CONTEXT}
      dockerfile: Dockerfile
    volumes:
      - ${SOURCE_PATH}/client/src:/usr/src/app/src
    container_name: ${CLIENT_CONTAINER_NAME}
    environment:
      VITE_ENV: development
      VITE_FIRESTORE_EMULATOR_PORT: ${VITE_FIRESTORE_EMULATOR_PORT}
      VITE_STORAGE_EMULATOR_PORT: ${VITE_STORAGE_EMULATOR_PORT}
      VITE_FIREBASE_AUTH_EMULATOR_PORT: ${VITE_FIREBASE_AUTH_EMULATOR_PORT}
      VITE_UI_EMULATOR_PORT: ${VITE_UI_EMULATOR_PORT}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "${CLIENT_PORT}:4200"
    networks:
      gmrscrap-network:
        ipv4_address: ${CLIENT_IP}
  server:
    build:
      context: ${SERVER_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${SERVER_CONTAINER_NAME}
    volumes:
      - ${SOURCE_PATH}/server:/usr/src/app
      - ${SOURCE_PATH}/stripe-secrets:/usr/src/app/secrets
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development
      DOCKER_HOST: ${DOCKER_IP}
      DOCKER_PORT: ${DOCKER_PORT}
      FIREBASE_IP: ${FIREBASE_IP}
      FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      FIREBASE_FUNCTIONS_EMULATOR_PORT: ${VITE_FIREBASE_FUNCTIONS_EMULATOR_PORT}
      FIRESTORE_EMULATOR_PORT: ${VITE_FIRESTORE_EMULATOR_PORT}
      STORAGE_EMULATOR_PORT: ${VITE_STORAGE_EMULATOR_PORT}
      FIREBASE_AUTH_EMULATOR_PORT: ${VITE_FIREBASE_AUTH_EMULATOR_PORT}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET_FILE: /usr/src/app/secrets/stripe_webhook_secret
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${SERVER_PORT}:1337"
    networks:
      gmrscrap-network:
        ipv4_address: ${SERVER_IP}

networks:
  gmrscrap-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
