name: ${APP_ID}
services:
  machine:
    build:
      context: ./machine
      dockerfile: Dockerfile
    container_name: ${APP_ID}-machine
    image: ${APP_ID}-machine
    volumes:
      - ./firebase.json:/usr/src/app/firebase.json
      - ./firebaseServiceAccount.json:/usr/src/app/firebaseServiceAccount.json
      - ./machine:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
      DOCKER_HOST: ${DOCKER_IPV4_ADDRESS}
      DOCKER_PORT: ${APP_DOCKER_PORT}
      MACHINE_BUILD_IMAGE_NAME: ${APP_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    networks:
      gmrs-network:
        ipv4_address: ${MACHINE_IPV4_ADDRESS}
    restart: "no"
    # Need to run inside docker
    entrypoint: ["npm", "run", "init"]

networks:
  gmrs-network:
    external: true
