version: "3.9"

services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    container_name: gmr_scrap_firebase
    ports:
      - "5001:5001"
      - "9100:9100"
      - "9199:9199"
      - "9099:9099"
      - "4000:4000"
    environment:
      ENDPOINT_URL: "http://host.docker.internal:1337"
      FIREBASE_FUNCTIONS_EMULATOR_HOST: "firebase:5001"
      FIRESTORE_EMULATOR_HOST: "firebase:9100"
      STORAGE_EMULATOR_HOST: "firebase:9199"
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:9099"
      UI_EMULATOR_HOST: "firebase:4000"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: gmr_scrap_client
    environment:
      VITE_ENV: development
    ports:
      - "4200:4200"
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gmr_scrap_server
    volumes:
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      - app-network
  machine:
    build:
      context: ./machine
      dockerfile: Dockerfile
    container_name: gmr_scrap_machine
    volumes:
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
