services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: ${PROJECT_ID}-stripe-cli
    working_dir: /usr/src/app
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    volumes:
      - ./stripe-secrets:/usr/src/app/secrets
    entrypoint: >
      sh -c "
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --print-secret > /usr/src/app/secrets/stripe_webhook_secret && 
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://${SERVER_IP}:${SERVER_PORT}/stripe/webhook
      "
  docker:
    image: docker:27.0-dind
    container_name: ${PROJECT_ID}-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "${DOCKER_PORT}:2375"
    working_dir: /usr/src/app
    networks:
      gmrs-network:
        ipv4_address: ${DOCKER_IPV4_ADDRESS}
  firebase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_ID}-firebase
    image: ${PROJECT_ID}-firebase
    volumes:
      - ./functions/index.js:/usr/src/app/functions/index.js
      - ./functions/src:/usr/src/app/functions/src
    environment:
      FIREBASE_PROJECT_ID: demo-${PROJECT_ID}
      SERVER_IP: ${SERVER_IPV4_ADDRESS}
    ports:
      - "${FIREBASE_EMULATOR_AUTHENTICATION}:9099"
      - "${FIREBASE_EMULATOR_UI}:4000"
      - "${FIREBASE_EMULATOR_FUNCTIONS}:5001"
      - "${FIREBASE_EMULATOR_FIRESTORE}:8080"
      - "${FIREBASE_EMULATOR_STORAGE}:9199"
      - "${FIREBASE_EMULATOR_HUB}:4400"
    networks:
      gmrs-network:
        ipv4_address: ${FIREBASE_IPV4_ADDRESS}
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${PROJECT_ID}-server
    image: ${PROJECT_ID}-server
    volumes:
      - ./server:/usr/src/app
      - ./stripe-secrets:/usr/src/app/secrets
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development
      MACHINE_BUILD_IMAGE_NAME: ${PROJECT_ID}

      DOCKER_HOST: ${DOCKER_IPV4_ADDRESS}
      DOCKER_PORT: ${DOCKER_PORT}

      FIREBASE_IP: ${FIREBASE_IPV4_ADDRESS}
      FIREBASE_PROJECT_ID: demo-${PROJECT_ID}
      FIREBASE_EMULATOR_FIRESTORE: ${FIREBASE_EMULATOR_FIRESTORE}

      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET_FILE: /usr/src/app/secrets/stripe_webhook_secret
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}

      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${SERVER_PORT}:1337"
    networks:
      gmrs-network:
        ipv4_address: ${SERVER_IPV4_ADDRESS}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    container_name: ${PROJECT_ID}-client
    image: ${PROJECT_ID}-client
    environment:
      VITE_ENV: development
      VITE_FIREBASE_EMULATOR_FIRESTORE: ${FIREBASE_EMULATOR_FIRESTORE}
      VITE_FIREBASE_EMULATOR_STORAGE: ${FIREBASE_EMULATOR_STORAGE}
      VITE_FIREBASE_EMULATOR_AUTHENTICATION: ${FIREBASE_EMULATOR_AUTHENTICATION}
      VITE_FIREBASE_PROJECT_ID: demo-${PROJECT_ID}

      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
      VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
    ports:
      - "${CLIENT_PORT}:4200"
    networks:
      gmrs-network:
        ipv4_address: ${CLIENT_IPV4_ADDRESS}

networks:
  gmrs-network:
    external: true
