version: "3.9"

services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    container_name: gmr_scrap_firebase
    ports:
      - "5001:5001"
      - "9100:9100"
      - "9199:9199"
      - "9099:9099"
      - "4000:4000"
    environment:
      FIREBASE_FUNCTIONS_EMULATOR_HOST: "firebase:5001"
      FIRESTORE_EMULATOR_HOST: "firebase:9100"
      STORAGE_EMULATOR_HOST: "firebase:9199"
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:9099"
      UI_EMULATOR_HOST: "firebase:4000"
    networks:
      - app-network
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: gmr_scrap_client
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gmr_scrap_server
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app/server
      - ./firebase.json:/usr/src/app/firebase.json
      - ./firebasekeys.json:/usr/src/app/firebasekeys.json
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      - app-network
  machine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmr_scrap_machine
    working_dir: /usr/src/app
    volumes:
      - ./machine:/usr/src/app/machine
      - ./firebase.json:/usr/src/app/firebase.json
      - ./firebasekeys.json:/usr/src/app/firebasekeys.json
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
