version: "3.9"

services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    working_dir: /usr/src/app
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    networks:
      app-network:
        ipv4_address: ${STRIPE_IP}
    volumes:
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/stripe-secrets:/usr/src/app/secrets
    entrypoint: >
      sh -c "
        # Start the first stripe listen in the background to print the secret
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to ${SERVER_IP}:${SERVER_PORT}/stripe/webhook --print-secret > /usr/src/app/secrets/stripe_webhook_secret & 
        # Run the second stripe listen for webhook forwarding
        stripe listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://${SERVER_IP}:${SERVER_PORT}/stripe/webhook
      "
  docker:
    image: ${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER_NAME}
    privileged: true
    volumes:
      - /var/lib/docker
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "${DOCKER_PORT}:2375"
    working_dir: ${DOCKER_WORKING_DIR}
    networks:
      app-network:
        ipv4_address: ${DOCKER_IP}
  machine:
    build:
      context: ${MACHINE_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${MACHINE_CONTAINER_NAME}
    volumes:
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/firebase.json:/usr/src/app/firebase.json
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/firebasekeys.json:/usr/src/app/firebasekeys.json
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/machine:/usr/src/app
    working_dir: ${MACHINE_WORKING_DIR}
    environment:
      NODE_ENV: development
      DOCKER_HOST: ${DOCKER_IP}
      DOCKER_PORT: ${DOCKER_PORT}
    networks:
      app-network:
        ipv4_address: ${MACHINE_IP}
    restart: "no"
    depends_on:
      - docker
    entrypoint: ["node", "init.js"]
  firebase:
    build:
      context: ${FIREBASE_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${FIREBASE_CONTAINER_NAME}
    ports:
      - "${FIREBASE_FUNCTIONS_EMULATOR_PORT}:5001"
      - "${FIRESTORE_EMULATOR_PORT}:9100"
      - "${STORAGE_EMULATOR_PORT}:9199"
      - "${FIREBASE_AUTH_EMULATOR_PORT}:9099"
      - "${UI_EMULATOR_PORT}:4000"
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      app-network:
        ipv4_address: ${FIREBASE_IP}
  client:
    build:
      context: ${CLIENT_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${CLIENT_CONTAINER_NAME}
    environment:
      VITE_ENV: development
      VITE_FIREBASE_EMULATOR_IP: ${FIREBASE_IP}
      VITE_FIREBASE_FUNCTIONS_EMULATOR_PORT: ${FIREBASE_FUNCTIONS_EMULATOR_PORT}
      VITE_FIRESTORE_EMULATOR_PORT: ${FIRESTORE_EMULATOR_PORT}
      VITE_STORAGE_EMULATOR_PORT: ${STORAGE_EMULATOR_PORT}
      VITE_FIREBASE_AUTH_EMULATOR_PORT: ${FIREBASE_AUTH_EMULATOR_PORT}
      VITE_UI_EMULATOR_PORT: ${UI_EMULATOR_PORT}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
    ports:
      - "${CLIENT_PORT}:4200"
    networks:
      app-network:
        ipv4_address: ${CLIENT_IP}
  server:
    build:
      context: ${SERVER_BUILD_CONTEXT}
      dockerfile: Dockerfile
    container_name: ${SERVER_CONTAINER_NAME}
    volumes:
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/stripe-secrets:/usr/src/app/secrets
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development
      DOCKER_HOST: ${DOCKER_IP}
      DOCKER_PORT: ${DOCKER_PORT}
      FIREBASE_IP: ${FIREBASE_IP}
      FIREBASE_FUNCTIONS_EMULATOR_PORT: ${FIREBASE_FUNCTIONS_EMULATOR_PORT}
      FIRESTORE_EMULATOR_PORT: ${FIRESTORE_EMULATOR_PORT}
      STORAGE_EMULATOR_PORT: ${STORAGE_EMULATOR_PORT}
      FIREBASE_AUTH_EMULATOR_PORT: ${FIREBASE_AUTH_EMULATOR_PORT}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET_FILE: /usr/src/app/secrets/stripe_webhook_secret
    ports:
      - "${SERVER_PORT}:1337"
    networks:
      app-network:
        ipv4_address: ${SERVER_IP}

networks:
  app-network:
    # external: true
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
