name: ${APP_ID}
services:
  machine:
    build:
      context: ./machine
      dockerfile: Dockerfile
    container_name: ${APP_ID}-machine
    image: ${APP_ID}-machine
    working_dir: /usr/src/app
    volumes:
      - ./certs:/certs
      - ./firebase.json:/usr/src/app/firebase.json
      - ./firebaseServiceAccount.json:/usr/src/firebaseServiceAccount.json
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      DOCKER_IPV4_ADDRESS: ${DOCKER_IPV4_ADDRESS}
      APP_DOCKER_PORT: ${APP_DOCKER_PORT}
      MACHINE_BUILD_IMAGE_NAME: ${APP_ID}
      APP_FIREBASE_PROJECT_ID: ${APP_FIREBASE_PROJECT_ID}
      APP_FIREBASE_IPV4_ADDRESS: ${APP_FIREBASE_IPV4_ADDRESS}
    networks:
      gmrs-network:
        ipv4_address: ${MACHINE_IPV4_ADDRESS}
    restart: "no"

networks:
  gmrs-network:
    external: true
