version: "3.9"

services:
  docker:
    image: docker:27.0-dind
    container_name: gmr_scrap_docker
    privileged: true
    volumes:
      - /var/lib/docker
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "2375:2375"
    working_dir: /usr/src/app
    networks:
      app-network:
        ipv4_address: 172.9.0.26
  machine:
    build:
      context: ./machine
      dockerfile: Dockerfile
    container_name: gmr_scrap_machine
    volumes:
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/firebase.json:/usr/src/app/firebase.json
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/firebasekeys.json:/usr/src/app/firebasekeys.json
      - /Users/shakhrillo/Desktop/m_main/codecanyon/gmr_scrap/demo/machine:/usr/src/app
    working_dir: /usr/src/app
    networks:
      app-network:
        ipv4_address: 172.9.0.48
    restart: "no"
    depends_on:
      - docker
    entrypoint: ["node", "init.js"]
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    container_name: gmr_scrap_firebase
    ports:
      - "5001:5001"
      - "9100:9100"
      - "9199:9199"
      - "9099:9099"
      - "4000:4000"
    environment:
      ENDPOINT_URL: "http://host.docker.internal:1337"
      FIREBASE_FUNCTIONS_EMULATOR_HOST: "firebase:5001"
      FIRESTORE_EMULATOR_HOST: "firebase:9100"
      STORAGE_EMULATOR_HOST: "firebase:9199"
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:9099"
      UI_EMULATOR_HOST: "firebase:4000"
    networks:
      app-network:
        ipv4_address: 172.9.0.25
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: gmr_scrap_client
    environment:
      VITE_ENV: development
    ports:
      - "4200:4200"
    networks:
      app-network:
        ipv4_address: 172.9.0.27
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: gmr_scrap_server
    volumes:
      - ./firebase.json:/usr/src/firebase.json
      - ./firebasekeys.json:/usr/src/firebasekeys.json
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      app-network:
        ipv4_address: 172.9.0.28

networks:
  app-network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.9.0.0/24
