console.log("settings.js loaded", process.env.CHROME_PATH);
module.exports = {
  launch: {
    // executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    headless: !true,
    protocolTimeout: 60000, // Set this to a higher value (in milliseconds)
    args: [
      "--autoplay-policy=user-gesture-required",
      "--disable-background-networking",
      "--disable-background-timer-throttling",
      "--disable-backgrounding-occluded-windows",
      "--disable-breakpad",
      "--disable-client-side-phishing-detection",
      "--disable-component-update",
      "--disable-default-apps",
      "--disable-dev-shm-usage",
      "--disable-domain-reliability",
      "--disable-extensions",
      "--disable-features=AudioServiceOutOfProcess",
      "--disable-hang-monitor",
      "--disable-ipc-flooding-protection",
      "--disable-notifications",
      "--disable-offer-store-unmasked-wallet-cards",
      "--disable-popup-blocking",
      "--disable-print-preview",
      "--disable-prompt-on-repost",
      "--disable-renderer-backgrounding",
      "--disable-setuid-sandbox",
      "--disable-speech-api",
      "--disable-sync",
      // '--hide-scrollbars',
      "--ignore-gpu-blacklist",
      "--metrics-recording-only",
      "--mute-audio",
      "--no-default-browser-check",
      "--no-first-run",
      "--no-pings",
      "--no-sandbox",
      "--no-zygote",
      "--password-store=basic",
      "--use-gl=swiftshader",
      "--use-mock-keychain",
      "--disable-gpu",
      "--disable-canvas-aa",
      "--disable-2d-canvas-clip-aa",
      "--disable-gl-drawing-for-tests",
      "--disable-default-apps",
      "--disable-sync",
      "--safebrowsing-disable-auto-update",
      "--disable-accelerated-2d-canvas",
      "--disk-cache-dir=/dev/null",
      "--disk-cache-size=0",
    ],
    defaultViewport: null,
    timeout: 30000,
  },
  goto: {
    waitUntil: "networkidle2",
    timeout: 30000,
  },
  viewport: {
    width: 800,
    height: 1000,
  },
  waitTime: 5000,
};
